allow-branch = ["main"]
sign-commit = false
sign-tag = false
tag-name = "v{{version}}"
tag-message = "Release {{crate_name}} {{version}}"
pre-release-commit-message = "chore: release {{crate_name}} {{version}}"
publish = false
push = true
